---
name: 01 Azure Landing Zones Continuous Integration
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      terraform_folder:
        description: 'Terraform folder to validate'
        required: true
        default: 'platform_shared'
        type: choice
        options:
          - 'platform_shared'
          - 'platform_amba'
          - 'platform_management'
          - 'platform_security'
      terraform_cli_version:
        description: 'Terraform CLI Version'
        required: true
        default: 'latest'
        type: string

jobs:
  validate_and_plan:
    uses: TysonTech-net/alz-mgmt-templates/.github/workflows/ci-template.yaml@main
    name: 'CI'
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    with:
      root_module_folder_relative_path: ${{ inputs.terraform_folder || 'platform_shared' }}
      terraform_cli_version: ${{ inputs.terraform_cli_version || 'latest' }}
